### ISSUE TITLE
error-throwing from neos.lang.fusion.resolve.ref.FusionReferenceBase$$

### ISSUE THREAD

**Issue by mad99** [cvette/intellij-neos#13] opened 2017-04-26 06:56 UTC
Hey Christian,
this error pops sometimes more or less.
___
IDE Fatal Errors / Comments:
de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$107/459784022.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
___
IDE Fatal Errors Details:
de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$107/459784022.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
java.lang.AbstractMethodError: de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase$$Lambda$107/459784022.resolve(Lcom/intellij/psi/PsiReference;Z)Ljava/lang/Object;
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.multiResolve(FusionReferenceBase.java:41)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at de.vette.idea.neos.lang.fusion.resolve.ref.FusionReferenceBase.resolve(FusionReferenceBase.java:56)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:403)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:380)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:247)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
___
Plugin: 0.1.12.SNAPSHOT
phpStorm: 2016.1.2

Hope will help you to bugfix.

Event Log:
![event log](https://cloud.githubusercontent.com/assets/6169308/25421669/31635fea-2a5e-11e7-97d1-4ba9f8778267.png)

**Comment by cvette** [comment] 2017-04-30 20:26
Can you provide the code that threw this exception? I saw this exception once before but couldn't reproduce it since then.

**Comment by mad99** [comment] 2017-05-01 07:47
I tried to understand, what the reason could be. Usually I work with phpStorm in 4 divided areas and growing numbers of tabs. At the end tons of open tabs.
Each change of focus from one tab to another, also in the same divide, throw one new line with the same error. Regardless if it is a fusion/html-fluid/scss/yaml/js File.

I reduced the numbers of tabs gently and restart phpStorm a view times, because the first error-throwing was at the start. At the end I had two not complicated fusion-Files open. Each one in the own Window-Division/Partition. Also there, the focus-change throws a new error. Also when I restart.
Reduce to one big window without no Partition/Tabs and a restart did stop the throwing. Now I'm on 4 Partition back, with 8 files. No error until now. Probebly at the beginning there were about 40 tabs. (Because the Settings for Tab limit is on 10). At the end of the day the tabs-number will be growing back around this number.
But until now unfortunately/fortunately I can't reproduce the error too. Maybe it will come back. Maybe it is not one particular file/code. Maybe the amount of tabs or something else really hard to detect for me/you.
Probably I have to restart phpStorm in virginity without dividing. Than grow up the amount of tabs gently like today. If Error throws again, I will send you more information, if I can find/define/recognize.

**Comment by mad99** [comment] 2017-05-01 09:17
Error throwing back, with 8 files in 4 Window-Divisions. Have restart with only 1 bigWindow. Now Error-Throwing after a while with 5 Tabs in 4 Divisions. 2 of them are the simple-yaml files 3 really simple and short fusion-Files: all 5 Files without errors (green OK-Sign in right top). 
I think it have to do with time and «?». I have also Plugin CodeGlance (Minimap similar to the one found in Sublime) in use. Maybe it is something like the interplay of plugins?
Is it possible to generate a more precisely or more cause-indicating error-info from phpStorm on my local machine?

**Comment by cvette** [comment] 2017-05-25 15:23
if you have a directory in a resource string it will cause an exception. This should be fixed with 5ce3b8479b7f42529e5d17c22c4afe83b1ce72dd. I'm closing this issue for now, as this is most likely the cause.

**Closed by cvette** 2017-05-25 15:23 UTC
Labels: bug, fusion
